name: my_food_reviews
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  geolocator: ^10.0.1
  geocoding: ^2.1.0
  geocode: ^1.0.3
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  firebase_core: ^2.16.0
  firebase_auth: ^4.10.0
  cloud_firestore: ^4.9.2
  firebase_storage: ^11.2.7
  cached_network_image: ^3.2.3
  intl: ^0.18.1  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/images/